I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/rpycodes/script_1_1.rpy", line 1179, in script
    ym "喵？"
Exception: Sayer 'ym' is not defined.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/rpycodes/script_1_1.rpy", line 1179, in script
    ym "喵？"
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\ast.py", line 881, in execute
    who = eval_who(self.who, self.who_fast)
  File "D:\1_file\gal\renpy-8.0.3-sdk\renpy\ast.py", line 774, in eval_who
    raise Exception("Sayer '%s' is not defined." % who)
Exception: Sayer 'ym' is not defined.

Windows-10-10.0.22621 AMD64
Ren'Py 8.0.3.22090809
我们之间的爱恋化作少女来谋杀我 1.0
Wed Oct 26 13:13:20 2022
